# Generated by Django 6.0.4 on 2026-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('alergias', models.JSONField(default=list)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('google_sheet_synced', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
